openapi: 3.0.0
info:
  title: Timelines API
  description: API for retrieving timelines of posts from followed users.
  version: 1.0.0
servers:
  - url: http://api.example.com/v1
    description: Main API server
paths:
  /users/{userId}/timeline:
    get:
      summary: Get user timeline
      description: Retrieve the latest posts from the users that the specified user follows.
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user whose timeline to retrieve.
          schema:
            type: string
            example: "12345"
        - name: limit
          in: query
          required: false
          description: The number of posts to retrieve (default is 20).
          schema:
            type: integer
            example: 20
        - name: page
          in: query
          required: false
          description: The page number for pagination.
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: A list of posts for the user's timeline.
          content:
            application/json:
              schema:
                type: object
                properties:
                  posts:
                    type: array
                    items:
                      type: object
                      properties:
                        postId:
                          type: string
                          example: "67890"
                        author:
                          type: string
                          example: "user123"
                        imageUrl:
                          type: string
                          example: "http://cdn.example.com/image.jpg"
                        caption:
                          type: string
                          example: "Enjoying the view!"
                        timestamp:
                          type: string
                          format: date-time
                          example: "2024-10-24T14:34:00Z"
        '400':
          description: Invalid request parameters (e.g., missing userId).
        '404':
          description: User not found or no posts available.
